### ISSUE TITLE
Unable to generate commit message

### ISSUE THREAD

**Issue by b-d-e** [0xble/commit#1]
Hey, thanks for creating this tool - looking forward to it making my workflow much more streamlined!

I'm having issues generating my commit messages - as far as I can tell the executable built properly and installed globally with cargo as intended. I have my OpenAI API key set as a global bash export variable, and can log it to the terminal so that seems okay. However, when trying to generate a commit message with my locally added changes, the following is outputted:
`✔ Got commit message!

Failed to generate commit message.`

(shown in full here:)
<img width="570" alt="Screenshot 2022-12-28 at 16 07 42" src="https://user-images.githubusercontent.com/18743860/209884362-07821ee3-1e04-46ac-b6e7-5d58288a09f3.png">

Looking at the OpenAI dashboard the API isn't getting queried via that key at all on their end.

Any pointers as to what might be the cause here, or how I can get some more verbose logs, would be appreciated!

**System information**
- MacBook Pro 2019, Intel Silicon. 
- macOS Ventura 13.0.1
- git version 2.38.1
- Shell: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)
- rustc 1.66.0 (69f9c33d7 2022-12-12)
- cargo 1.66.0 (d65d197ad 2022-11-15)

**Comment by 0xble** [comment]
Seems to be an error from the OpenAI API, but not sure what it is. I've improved the error handling to fix this, can you reinstall (using `cargo install`) and try running again? There is a high change it'll still give an error. If it happens, send it here so I can try fixing it.

**Comment by b-d-e** [comment]
Thanks for that, helped me trace it down and was an error on my end - apologies for hassling you! 
For anyone else who runs into a similar issue, it turns out that while I had credits showing in my OpenAI account they had expired, as apparently the free grant only lasts for 3 months (so it showed as having $x amount of credits which I assumed were valid). Thanks for your help - it's working well now I've linked up my card!
